# Generated by Django 4.1.7 on 2023-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
