# Generated by Django 4.1.7 on 2023-03-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDFfilelocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelTable(
            name='author',
            table='PDFfilelocator_author',
        ),
    ]
