# Generated by Django 4.1.7 on 2023-03-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDFfilelocator', '0002_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
