# Generated by Django 4.1.7 on 2023-03-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDFfilelocator', '0003_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFfilelocator.pdffile')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=10)),
                ('y', models.CharField(max_length=10)),
                ('input_data', models.CharField(max_length=255)),
                ('font_size', models.IntegerField()),
                ('history_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFfilelocator.historyitem')),
            ],
        ),
    ]
