# Generated by Django 4.1.7 on 2023-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFfilelocator', '0006_historyitem_file_name_historyitem_json_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='file_name',
            field=models.CharField(default='pdfname.pdf', max_length=100),
        ),
    ]
